name: Build & Export IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project stashy.xcodeproj -scheme stashy

      # 1. ARCHIVE
      - name: Archive app
        run: |
          xcodebuild \
            -project stashy.xcodeproj \
            -scheme stashy \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/stashy.xcarchive \
            clean archive \
            CODE_SIGNING_ALLOWED=NO

      # 2. EXPORT IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/stashy.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      # 3. Upload IPA
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: stashy-ipa
          path: build/*.ipa
